language: haskell
cabal: "3.2"

ghc:
- "8.6.5"
- "8.8.4"
- "8.10.3"

before_install: travis_retry cabal new-update

install: cabal new-install --lib --only-dependencies

script: cabal new-build

cache:
  directories:
  - $HOME/.cabal
