name:                fhetero
version:             0.1.5.0
github:              burningwitness/fhetero
license:             BSD3
license-file:        LICENSE
author:              Oleksii Divak
maintainer:          Oleksii Divak <frozenwitness@gmail.com>
copyright:           (c) 2021, Oleksii Divak

extra-source-files:
- README.md

synopsis:            Heterogenous containers wrapped into functors
category:            Data

description:         Please see the README on GitHub at <https://github.com/burningwitness/fhetero#readme>

dependencies:
- base >= 4.12 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src

default-extensions:
- NoImplicitPrelude
